blank_issues_enabled: false
contact_links:
  - name: Download on CurseForge
    url: https://www.curseforge.com/minecraft/mc-mods/resonance-amethyst-overhaul
    about: Get official Resonance releases from CurseForge.
  - name: Download on Modrinth
    url: https://modrinth.com/mod/resonance-amethyst-overhaul
    about: Get official Resonance releases from Modrinth.
